name: Verify unwanted versioned conflicts

on: [pull_request]

jobs:
  merge_conflict_job:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0
